apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodename-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodename
  template:
    metadata:
      labels: 
        app: nodename
    spec:
      containers:
       - name: nodename-pod
         image: nginx
      nodeName: gke-manoj-k8s-k8s-pool-f2e75553-2tro
